# Generated by Django 6.0.3 on 2026-04-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancereport',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='attendancereport',
            name='attendance__user_id_053df4_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancereport',
            name='attendance__user_id_3e10d8_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancereport',
            name='attendance__user_id_46187d_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendancereport',
            name='attendance__start_d_497334_idx',
        ),
        migrations.DeleteModel(
            name='AttendanceReport',
        ),
    ]
