# Generated by Django 5.2.7 on 2025-11-19 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('primary_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, help_text='Official website ', max_length=500, null=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Total pax capacity')),
                ('price_per_event', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rooms', models.PositiveSmallIntegerField(default=0)),
                ('floors', models.PositiveSmallIntegerField(default=0)),
                ('parking_slots', models.JSONField(blank=True, default=dict, null=True)),
                ('external_decorators_allow', models.BooleanField(default=False)),
                ('external_caterers_allow', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list, null=True)),
                ('seating_arrangement', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_venues', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(blank=True, help_text='Staff assigned to this venue', limit_choices_to={'user_type': 'VSRE_STAFF'}, related_name='assigned_venues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('primary_contact', models.CharField(max_length=15, unique=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('website', models.URLField(blank=True, help_text='Official website', max_length=500, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('quickInfo', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_services', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(blank=True, help_text='Staff assigned to this service', limit_choices_to={'user_type': 'VSRE_STAFF'}, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_of_venue', to='venue_manager.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('total_quantity', models.PositiveIntegerField(default=1)),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('sell_price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_price_per_unit_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_resource', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ManyToManyField(blank=True, help_text='Staff assigned to this resource', limit_choices_to={'user_type': 'VSRE_STAFF'}, related_name='assigned_resource', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_of_service', to='venue_manager.service')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources_of_venue', to='venue_manager.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entety_photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='venue_manag_content_1c72df_idx')],
            },
        ),
    ]
