# Generated by Django 5.2.7 on 2025-11-21 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='photos',
            name='venue_manag_content_1c72df_idx',
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(default=None, upload_to='entity_photos/'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['owner', 'is_active'], name='venue_manag_owner_i_779be8_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['available_quantity'], name='venue_manag_availab_271972_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['owner', 'is_active'], name='venue_manag_owner_i_71218f_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['owner', 'is_active'], name='venue_manag_owner_i_917100_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['is_active', 'is_deleted'], name='venue_manag_is_acti_f70edd_idx'),
        ),
    ]
