# Generated by Django 5.2.7 on 2025-11-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0002_remove_photos_venue_manag_content_1c72df_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='bengaluru', max_length=200),
            preserve_default=False,
        ),
    ]
