# Generated by Django 5.2.7 on 2025-11-25 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0004_alter_resource_owner_alter_service_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='service',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='manager',
        ),
        migrations.AddField(
            model_name='resource',
            name='manager',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, related_name='managed_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='manager',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, related_name='managed_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venue',
            name='manager',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER']}, related_name='managed_venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
