# Generated by Django 5.2.7 on 2025-11-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0005_remove_resource_manager_remove_service_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_image/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_image/'),
        ),
    ]
