# Generated by Django 5.2.7 on 2025-11-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0006_service_logo_venue_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(default='Bengaluru', max_length=100),
            preserve_default=False,
        ),
    ]
