# Generated by Django 5.2.7 on 2025-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0008_service_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='primary_contact',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='service',
            name='primary_contact',
        ),
        migrations.RemoveField(
            model_name='service',
            name='secondary_contact',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='secondary_contact',
        ),
        migrations.AddField(
            model_name='service',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='quickInfo',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='service',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
