# Generated by Django 5.2.7 on 2025-12-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0009_rename_primary_contact_venue_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='quickInfo',
            new_name='quick_info',
        ),
    ]
