# Generated by Django 5.2.7 on 2026-01-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_location'),
        ('venue_manager', '0010_rename_quickinfo_service_quick_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.AddField(
            model_name='venue',
            name='location',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue_location', to='booking.location'),
            preserve_default=False,
        ),
    ]
