# Generated by Django 5.2.7 on 2026-01-10 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_location_unique_full_address'),
        ('venue_manager', '0011_remove_venue_address_remove_venue_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_location', to='booking.location'),
        ),
    ]
