# Generated by Django 5.2.7 on 2026-01-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_remove_location_unique_full_address'),
        ('venue_manager', '0012_alter_venue_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venue_location', to='booking.location'),
        ),
    ]
