# Generated by Django 5.2.7 on 2026-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_manager', '0013_alter_venue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='venue',
        ),
        migrations.AddField(
            model_name='service',
            name='venue',
            field=models.ManyToManyField(blank=True, related_name='services_of_venue', to='venue_manager.venue'),
        ),
    ]
