# Generated by Django 5.2.7 on 2025-12-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_remove_payrollpayment_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarystructure',
            old_name='daily_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='fortnight_rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='hour_rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='monthly_rate',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='weekly_rate',
        ),
    ]
