# Generated by Django 5.2.7 on 2025-12-10 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_rename_daily_rate_salarystructure_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='is_increment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='user',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL),
        ),
    ]
