# Generated by Django 5.2.7 on 2025-12-19 04:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_salarystructure_advance_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='salarystructure',
            unique_together={('user', 'effective_from')},
        ),
    ]
