# Generated by Django 5.2.7 on 2025-12-27 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_alter_salarystructure_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='Unique salary transaction ID', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Salary amount', max_digits=12)),
                ('payment_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('FORTNIGHTLY', 'Fortnightly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('HOURLY', 'Hourly')], max_length=20)),
                ('payment_period_start', models.DateField()),
                ('payment_period_end', models.DateField()),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank ref / UTR / cheque number', max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='salary_receipts/')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When salary was paid', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payer', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_receiver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salary Payment',
                'verbose_name_plural': 'Salary Payments',
                'ordering': ['-payment_period_start'],
            },
        ),
        migrations.DeleteModel(
            name='PayRollPayment',
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['receiver', '-processed_at'], name='payroll_sal_receive_a97019_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['status', 'created_at'], name='payroll_sal_status_cbd8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['transaction_id'], name='payroll_sal_transac_313c30_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salarytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('payment_period_end__gte', models.F('payment_period_start'))), name='valid_salary_period'),
        ),
    ]
