# Generated by Django 5.2.7 on 2025-12-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_salarytransaction_delete_payrollpayment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarystructure',
            old_name='rate',
            new_name='base_salary',
        ),
    ]
