# Generated by Django 5.2.7 on 2025-12-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_rename_rate_salarystructure_base_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarystructure',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
