# Generated by Django 5.2.7 on 2025-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_salarystructure_total_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarystructure',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='base_salary',
        ),
        migrations.RemoveField(
            model_name='salarystructure',
            name='is_increment',
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='change_type',
            field=models.CharField(choices=[('BASE_SALARY', 'Base Salary'), ('INCREMENT', 'Increment'), ('ADVANCE', 'Advance'), ('LOAN', 'Loan')], default='BASE_SALARY', max_length=20),
        ),
    ]
