# Generated by Django 5.2.7 on 2025-12-30 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_rename_total_salary_salarystructure_final_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(condition=models.Q(('change_type', 'BASE_SALARY')), fields=('user',), name='unique_base_salary_per_user'),
        ),
    ]
