# Generated by Django 5.2.7 on 2026-01-01 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_salarystructure_unique_base_salary_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salarytransaction',
            name='salary_amount_positive',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='amount',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid to employee', max_digits=12),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount yet to be paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount payable to employee', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='salarytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_payable_amount__gt', 0)), name='total_payable_amount_positive'),
        ),
    ]
