# Generated by Django 5.2.7 on 2026-01-02 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_remove_salarytransaction_salary_amount_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='payer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payer', to=settings.AUTH_USER_MODEL),
        ),
    ]
