# Generated by Django 5.2.7 on 2026-01-02 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_alter_salarytransaction_payer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
