# Generated by Django 5.2.7 on 2026-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_alter_salarytransaction_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarytransaction',
            old_name='remaining_amount',
            new_name='remaining_payment',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='total_payable_amount',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='current_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
