# Generated by Django 5.2.7 on 2026-01-02 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_rename_remaining_amount_salarytransaction_remaining_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarytransaction',
            options={'ordering': ['-payment_period_start']},
        ),
        migrations.RemoveIndex(
            model_name='salarytransaction',
            name='payroll_sal_transac_313c30_idx',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='current_payment',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='total_payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='payer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'VSRE_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
