# Generated by Django 5.2.7 on 2026-01-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_alter_salarytransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='salarytransaction',
            name='payroll_sal_receive_a97019_idx',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='salarytransaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='user',
            field=models.ForeignKey(default=5, limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['user', '-processed_at'], name='payroll_sal_user_id_a41c33_idx'),
        ),
    ]
