# Generated by Django 5.2.7 on 2026-01-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_remove_salarytransaction_payroll_sal_receive_a97019_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
