# Generated by Django 5.2.7 on 2026-01-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_alter_salarytransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
