# Generated by Django 5.2.7 on 2026-01-06 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_salaryreport_delete_salarytransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salarystructure',
            name='unique_base_salary_per_user',
        ),
        migrations.AddConstraint(
            model_name='salarystructure',
            constraint=models.UniqueConstraint(condition=models.Q(('change_type', 'BASE_SALARY')), fields=('user', 'effective_from'), name='unique_base_salary_per_user_per_date'),
        ),
    ]
