# Generated by Django 5.2.7 on 2026-01-07 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_remove_salarystructure_unique_base_salary_per_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Actual amount paid', max_digits=12)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('OTHER', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Bank / UPI / cheque reference', max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_report', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='payroll.salaryreport')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='amount_paid_non_negative')],
            },
        ),
    ]
