# Generated by Django 5.2.7 on 2026-01-07 07:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_salarytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
