# Generated by Django 5.2.7 on 2026-01-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_salaryreport_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytransaction',
            name='salary_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payroll.salaryreport'),
        ),
    ]
