# Generated by Django 6.0.3 on 2026-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_alter_salarytransaction_salary_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='esi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='pf_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
