# Generated by Django 6.0.3 on 2026-09-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_salarystructure_esi_amount_salarystructure_pf_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarystructure',
            name='salary_mode',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('OTHER', 'Other')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
