# Generated by Django 6.0.3 on 2026-09-19 16:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.core.management.color import no_style


def copy_attendance_data(apps, schema_editor):
    """Copy legacy attendance tables when upgrading an existing deployment."""
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())
    source_status = "attendance_attendancestatus"
    source_attendance = "attendance_attendance"
    if not {source_status, source_attendance}.issubset(existing_tables):
        return

    AttendanceStatus = apps.get_model("payroll", "AttendanceStatus")
    Attendance = apps.get_model("payroll", "Attendance")
    quote = schema_editor.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            f"INSERT INTO {quote(AttendanceStatus._meta.db_table)} "
            "(id, code, label, is_active, owner_id) "
            f"SELECT id, code, label, is_active, owner_id FROM {quote(source_status)}"
        )
        cursor.execute(
            f"INSERT INTO {quote(Attendance._meta.db_table)} "
            "(id, date, duration, reason, created_at, updated_at, user_id, status_id) "
            f"SELECT id, date, duration, reason, created_at, updated_at, user_id, status_id "
            f"FROM {quote(source_attendance)}"
        )
        for sql in connection.ops.sequence_reset_sql(no_style(), [AttendanceStatus, Attendance]):
            cursor.execute(sql)


def reverse_copy_attendance_data(apps, schema_editor):
    # The legacy tables are intentionally retained as an upgrade backup.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_salarystructure_salary_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(limit_choices_to={'user_type': 'VSRE_OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Status',
                'verbose_name_plural': 'Attendance Statuses',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(limit_choices_to={'user_type__in': ['VSRE_MANAGER', 'LINE_MANAGER', 'VSRE_STAFF']}, on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='payroll.attendancestatus')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='payroll_att_user_id_98af05_idx'), models.Index(fields=['user', '-date'], name='payroll_att_user_id_08de27_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='payroll_attendance_user_date_unique')],
            },
        ),
        migrations.RunPython(copy_attendance_data, reverse_copy_attendance_data),
    ]
