# Generated by Django 6.0.3 on 2026-09-22 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_attendancestatus_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month')),
                ('present_days', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('half_days', models.PositiveIntegerField(default=0)),
                ('paid_leave_days', models.PositiveIntegerField(default=0)),
                ('payable_days', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cumulative_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_finalized', models.BooleanField(default=False, help_text='True once the month is closed; row becomes immutable')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['user', '-month'], name='payroll_pay_user_id_8b9df9_idx')],
                'unique_together': {('user', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the payroll month this payment applies to, e.g. 2026-08-01')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_on'],
                'indexes': [models.Index(fields=['user', 'month'], name='payroll_sal_user_id_705823_idx')],
            },
        ),
    ]
