# Generated by Django 6.0.3 on 2026-09-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_payrollrecord_salarypayment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='payrollrecord',
            name='payroll_pay_user_id_8b9df9_idx',
        ),
        migrations.RemoveIndex(
            model_name='salarypayment',
            name='payroll_sal_user_id_705823_idx',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='salarypayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PayrollRecord',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
