# Generated by Django 6.0.3 on 2026-09-22 09:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_alter_payrollrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryreport',
            name='absent_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='half_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='is_finalized',
            field=models.BooleanField(default=False, help_text='True once the month is closed; row becomes immutable'),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='paid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='payable_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='present_days + half_days * 0.5 + paid_leave_days', max_digits=5),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='present_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salaryreport',
            name='unpaid_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
