# Generated by Django 6.0.3 on 2026-09-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_salaryreport_absent_days_salaryreport_half_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salarytransaction',
            name='amount_paid_non_negative',
        ),
        migrations.AddField(
            model_name='salarytransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Actual date and time when the payment was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, help_text='Actual amount paid.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Bank / UPI / cheque reference.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salarytransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when the transaction reached a final state.', null=True),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['salary_report', 'status'], name='salary_tx_report_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['paid_at'], name='salary_tx_paid_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='salarytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='salary_transaction_amount_paid_non_negative'),
        ),
    ]
