# Generated by Django 6.0.3 on 2026-09-22 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_user_from_salary_report(apps, schema_editor):
    SalaryTransaction = apps.get_model('payroll', 'SalaryTransaction')
    SalaryReport = apps.get_model('payroll', 'SalaryReport')

    from django.db.models import OuterRef, Subquery

    SalaryTransaction.objects.update(
        user_id=Subquery(
            SalaryReport.objects.filter(
                pk=OuterRef('salary_report_id')
            ).values('user_id')[:1]
        )
    )


def reverse_noop(apps, schema_editor):
    # Reversing this migration just drops the field (handled by the
    # RemoveField reverse of AddField); nothing to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_remove_salarytransaction_amount_paid_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: add the field as nullable so existing rows don't violate
        # a NOT NULL constraint.
        migrations.AddField(
            model_name='salarytransaction',
            name='user',
            field=models.ForeignKey(
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salary_transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # Step 2: backfill user_id from salary_report.user_id for every
        # existing row.
        migrations.RunPython(populate_user_from_salary_report, reverse_noop),

        # Step 3: now that every row has a user, enforce NOT NULL.
        migrations.AlterField(
            model_name='salarytransaction',
            name='user',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='salary_transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AddIndex(
            model_name='salarytransaction',
            index=models.Index(fields=['user', 'status'], name='salary_tx_user_status_idx'),
        ),
    ]