# Generated by Django 5.2.7 on 2026-03-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('operational', 'operational'), ('system', 'System'), ('alert', 'Alert'), ('task', 'Task')], default='system', max_length=20),
        ),
    ]
