# Generated by Django 6.0.3 on 2026-04-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notificationpreference_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notif_type',
            new_name='notify_type',
        ),
    ]
