# Generated by Django 6.0.3 on 2026-04-17 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0005_rename_notif_type_notification_notify_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notify_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('operational', 'Operational'), ('system', 'System'), ('alert', 'Alert'), ('task', 'Task')], db_index=True, default='system', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('alert', 'In-App Alert')], db_index=True, default='alert', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='ContentType of the model that triggered this notification.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra_data',
            field=models.JSONField(blank=True, help_text='Optional structured payload (e.g. action URLs, deep links, task IDs).', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True, default='', help_text='Error detail if delivery failed.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the object that triggered this notification.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The VSRE owner under whose account this notification was triggered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Email address captured at notification creation time.', max_length=254),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number captured at notification creation time (E.164 preferred).', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of delivery attempts made.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='If set, notification should be dispatched at this time.', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User receiving this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal reference name for this template.', max_length=120)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('alert', 'In-App Alert')], max_length=20)),
                ('category', models.CharField(choices=[('operational', 'Operational'), ('system', 'System'), ('alert', 'Alert'), ('task', 'Task')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', help_text='Used as the email subject line. Ignored for SMS/WhatsApp/Alert.', max_length=255)),
                ('body', models.TextField(help_text='Message body. Use {{ variable_name }} for dynamic substitution.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owning account. Null means this is a platform-level template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template this notification was generated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notification.notificationtemplate'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status'], name='notificatio_recipie_417fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel', 'category'], name='notificatio_channel_349d97_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['owner', 'created_at'], name='notificatio_owner_i_9cfaef_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_7a28c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('owner', 'name', 'channel')},
        ),
    ]
