# Generated by Django 6.0.3 on 2026-04-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_notification_options_remove_notification_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('operational', 'Operational'), ('functional', 'Functional'), ('alert', 'Alert'), ('task', 'Task')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('voice', 'Voice'), ('in_app', 'In-App Alert')], db_index=True, max_length=20),
        ),
    ]
