# Generated by Django 5.2.7 on 2025-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('VSRE_OWNER', 'VSRE Owner'), ('VSRE_MANAGER', 'VSRE Manager'), ('LINE_MANAGER', 'Line Manager'), ('VSRE_STAFF', 'VSRE Staff'), ('CUSTOMER', 'Customer')], max_length=30),
        ),
    ]
