# Generated by Django 5.2.7 on 2025-11-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingmodel',
            name='max_resources',
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='max_services',
        ),
        migrations.RemoveField(
            model_name='pricingmodel',
            name='max_venues',
        ),
    ]
