# Generated by Django 5.2.7 on 2025-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, storage={'API_KEY': '636789668889275', 'API_SECRET': 'VFqjZOfuu2LQMD3t7whE7CiOYBk', 'CLOUD_NAME': 'dgbwzcbct'}, upload_to='profile_photos/'),
        ),
    ]
