# Generated by Django 5.2.7 on 2025-12-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_pricingmodel_max_resources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verified_document',
            field=models.FileField(blank=True, null=True, upload_to='staff_document/'),
        ),
    ]
