# Generated by Django 5.2.7 on 2025-12-26 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_verified_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhierarchy',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Top-level owner for this user hierarchy.', limit_choices_to={'user_type': 'VSRE_OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
