# Generated by Django 5.2.7 on 2026-01-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_profile_pic'),
        ('accounts', '0005_alter_userhierarchy_owner'),
    ]

    operations = [
    ]
