# Generated by Django 5.2.7 on 2026-01-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('FULLTIME', 'Fulltime'), ('PARTTIME', 'Parttime'), ('TERMINATED', 'Terminated'), ('VIRTUAL', 'Virtual'), ('PPO', 'PPO'), ('VENDOR', 'Vendor')], max_length=50, null=True),
        ),
    ]
