# Generated by Django 6.0.3 on 2026-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_passwordresetotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('FULLTIME', 'Fulltime'), ('PARTTIME', 'Parttime'), ('VIRTUAL', 'Virtual'), ('PPO', 'PPO'), ('VENDOR', 'Vendor')], max_length=50, null=True),
        ),
    ]
