# Generated by Django 6.0.3 on 2026-05-29 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffForHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('vendor_name', models.CharField(max_length=120)),
                ('available_from', models.DateField()),
                ('available_for', models.JSONField(blank=True, null=True)),
                ('language', models.JSONField(blank=True, null=True)),
                ('skill', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hire_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff for Hire',
                'verbose_name_plural': 'Staff for Hire',
                'ordering': ['-created_at'],
                'unique_together': {('staff_name', 'vendor_name')},
            },
        ),
    ]
