# Generated by Django 6.0.3 on 2026-09-16 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_mobile_number'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('FULLTIME', 'Fulltime'), ('PARTTIME', 'Parttime'), ('VIRTUAL', 'Virtual'), ('PPO', 'PPO'), ('VENDOR', 'Vendor')], max_length=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=120, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('order_types', models.JSONField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('target_percent', models.FloatField(blank=True, null=True)),
                ('qc_required', models.BooleanField(default=False)),
                ('pf_applicable', models.BooleanField(default=False)),
                ('pf_number', models.CharField(blank=True, max_length=30, null=True)),
                ('uan_number', models.CharField(blank=True, help_text='12-digit Universal Account Number', max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='UAN must be exactly 12 digits.', regex='^\\d{12}$')])),
                ('esi_applicable', models.BooleanField(default=False)),
                ('esi_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='ESI number must be 10 to 17 digits.', regex='^\\d{10,17}$')])),
                ('esi_dispensary', models.CharField(blank=True, max_length=120, null=True)),
                ('shift_effective_from', models.DateField(blank=True, help_text='Date this employee started on `shift`.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_overnight', models.BooleanField(default=False)),
                ('weekly_off_days', models.JSONField(blank=True, default=list, help_text='List of WeekDay values, e.g. [5, 6]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_working_day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='order_types',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='qc_required',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='target_percent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type', 'is_deleted'], name='accounts_cu_user_ty_7d9202_idx'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='accounts.shiftschedule'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['category'], name='accounts_em_categor_bb2076_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['employee_id'], name='accounts_em_employe_51b309_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['pf_number'], name='accounts_em_pf_numb_02378c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['esi_number'], name='accounts_em_esi_num_ae6b82_idx'),
        ),
    ]
