# Generated by Django 6.0.3 on 2026-09-16 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_employeeprofile_shiftschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='cost_center',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, help_text="Employee's HR department. Distinct from UserHierarchy.department, which reflects org reporting structure.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(blank=True, help_text="Job title, e.g. 'Senior Technician'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='rehired_status',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='shiftschedule',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Emp First Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Emp Last Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('VSRE_OWNER', 'VSRE Owner'), ('VSRE_MANAGER', 'VSRE Manager'), ('LINE_MANAGER', 'Line Manager'), ('VSRE_STAFF', 'VSRE Staff'), ('CUSTOMER', 'Customer')], max_length=30, verbose_name='Emp Role'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='DOJ'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='last_working_day',
            field=models.DateField(blank=True, null=True, verbose_name='LWD'),
        ),
    ]
