# Generated by Django 6.0.3 on 2026-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_customuser_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='termination_type',
            field=models.CharField(blank=True, choices=[('VOLUNTARY', 'Voluntary'), ('INVOLUNTARY', 'Involuntary')], max_length=20, null=True),
        ),
    ]
