# Generated by Django 5.2.7 on 2025-12-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='booking_pat_last_na_cdd83b_idx',
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(help_text='User who registered this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['registered_by'], name='booking_pat_registe_fdd519_idx'),
        ),
    ]
