# Generated by Django 5.2.7 on 2025-12-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_patient_booking_pat_last_na_cdd83b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_documents',
            field=models.FileField(default=None, help_text='Upload related document', upload_to='patient_documents/'),
            preserve_default=False,
        ),
    ]
