# Generated by Django 5.2.7 on 2025-12-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_patient_patient_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
