# Generated by Django 5.2.7 on 2026-01-01 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_patient_allergies_alter_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='year_of_retirement',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
