# Generated by Django 5.2.7 on 2026-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_patient_year_of_retirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('OPD', 'OPD'), ('PARTNER', 'Partner'), ('CLIENT', 'Client')], max_length=20)),
                ('building_name', models.CharField(max_length=250)),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250, null=True)),
                ('locality', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
