# Generated by Django 5.2.7 on 2026-01-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('building_name', 'address_line1', 'address_line2', 'locality', 'city', 'state', 'postal_code'), name='unique_full_address'),
        ),
    ]
