# Generated by Django 5.2.7 on 2026-01-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_location_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_full_address',
        ),
    ]
