# Generated by Django 5.2.7 on 2026-01-23 11:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_package'),
        ('venue_manager', '0013_alter_venue_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-registration_date'], 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddField(
            model_name='package',
            name='period',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], default='IN_HOUSE', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_documents',
            field=models.FileField(upload_to='patient_documents/'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('venue_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('services_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_BE_STARTED', 'Yet To Be Started'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], default='DRAFT', max_length=25)),
                ('continue_booking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_created', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='venue_manager.venue')),
                ('venue_package', models.ForeignKey(blank=True, limit_choices_to={'content_type__model': 'venue'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_bookings', to='booking.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_BE_STARTED', 'Yet To Be Started'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], default='DRAFT', max_length=25)),
                ('service_total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='booking.booking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_instances', to='venue_manager.service')),
                ('service_package', models.ForeignKey(blank=True, limit_choices_to={'content_type__model': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_bookings', to='booking.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_for', models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service')], default='VENUE', help_text='VENUE: venue + services | SERVICE: standalone services', max_length=20)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_bill_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remain_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='PAYMENT', max_length=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('service_bookings', models.ManyToManyField(blank=True, related_name='invoices', to='booking.bookingservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='booking_boo_user_id_4f3fce_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['patient', '-created_at'], name='booking_boo_patient_717fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_boo_status_e01616_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'start_datetime'], name='booking_boo_venue_i_095396_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingservice',
            index=models.Index(fields=['booking', 'service'], name='booking_boo_booking_8db845_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingservice',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='booking_boo_start_d_031e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicetransaction',
            index=models.Index(fields=['booking', 'invoice_for'], name='booking_inv_booking_d43f52_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicetransaction',
            index=models.Index(fields=['status', '-created_at'], name='booking_inv_status_f3b20f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicetransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='booking_inv_transac_7b8ce6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicetransaction',
            index=models.Index(fields=['invoice_id'], name='booking_inv_invoice_233449_idx'),
        ),
    ]
