# Generated by Django 5.2.7 on 2026-01-22 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_package_options_alter_patient_options_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='Auto-generated invoice number', max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('BOOKING_AND_SERVICES', 'Booking + Services'), ('BOOKING_ONLY', 'Booking Only'), ('SERVICE_ONLY', 'Service Only')], help_text='Type of invoice: Booking+Services, Booking Only, or Service Only', max_length=25)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, help_text='Subtotal before tax and discount', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount after tax and discount', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid so far', max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining amount to be paid', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, help_text='Auto-generated transaction number', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], db_index=True, default='PAYMENT', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NET_BANKING', 'Net Banking'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Payment gateway ID, cheque number, transaction ID, etc.', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Transaction description or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoicetransaction',
            name='service_bookings',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['-created_at'], 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-registration_date'], 'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='booking_loc_locatio_89e5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city', 'state'], name='booking_loc_city_de1fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['content_type', 'object_id'], name='booking_pac_content_2876da_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['package_type', 'is_active'], name='booking_pac_package_78013e_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['owner', '-created_at'], name='booking_pac_owner_i_210f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='booking_pat_first_n_3157ff_idx'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Required for BOOKING_AND_SERVICES and BOOKING_ONLY types', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(help_text='Patient/customer for this invoice', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_bookings',
            field=models.ManyToManyField(blank=True, help_text='Services included in this invoice', related_name='invoices', to='booking.bookingservice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(help_text='User who created the booking', on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(help_text='User who recorded this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice this transaction is for', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking.invoice'),
        ),
        migrations.DeleteModel(
            name='InvoiceTransaction',
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='booking_inv_invoice_b6965b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-created_at'], name='booking_inv_status_b1c734_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'status'], name='booking_inv_invoice_dadee4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', '-created_at'], name='booking_inv_patient_4e5aa5_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='booking_inv_due_dat_49da8f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_number'], name='booking_tra_transac_250f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['invoice', '-created_at'], name='booking_tra_invoice_1109b6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='booking_tra_transac_03166b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['payment_method'], name='booking_tra_payment_277c12_idx'),
        ),
    ]
