# Generated by Django 5.2.7 on 2026-01-27 10:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_invoice_options_and_more'),
        ('venue_manager', '0013_alter_venue_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='service_package',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='service_bookings',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.CreateModel(
            name='InvoiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_BE_STARTED', 'Yet To Be Started'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], db_index=True, default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.venue')),
                ('venue_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bookings', to='booking.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_BE_STARTED', 'Yet To Be Started'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], db_index=True, default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='booking.invoicebooking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue_manager.service')),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='booking.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TotalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='booking.invoicebooking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
                ('service_bookings', models.ManyToManyField(blank=True, related_name='invoices', to='booking.invoicebookingservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank')], db_index=True, max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID, check number, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.totalinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingService',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddIndex(
            model_name='invoicebooking',
            index=models.Index(fields=['user', 'status'], name='booking_inv_user_id_85fe23_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebooking',
            index=models.Index(fields=['patient', 'created_at'], name='booking_inv_patient_7befa3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebooking',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='booking_inv_start_d_19799e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebookingservice',
            index=models.Index(fields=['booking', 'status'], name='booking_inv_booking_a0661f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebookingservice',
            index=models.Index(fields=['service', 'created_at'], name='booking_inv_service_6aa652_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicebookingservice',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='booking_inv_start_d_055b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['patient', 'status'], name='booking_tot_patient_7b5699_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['user', 'created_at'], name='booking_tot_user_id_929181_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['status', 'due_date'], name='booking_tot_status_b6c8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'created_at'], name='booking_pay_invoice_0b8c79_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', 'method'], name='booking_pay_patient_a7a6c5_idx'),
        ),
    ]
