# Generated by Django 5.2.7 on 2026-01-27 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_invoice_booking_remove_bookingservice_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebooking',
            name='venue_package',
            field=models.ForeignKey(limit_choices_to={'content_type__model': 'venue'}, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bookings', to='booking.package'),
        ),
        migrations.AlterField(
            model_name='invoicebookingservice',
            name='service_package',
            field=models.ForeignKey(limit_choices_to={'content_type__model': 'service'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='booking.package'),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='booking.invoicebooking'),
        ),
    ]
