# Generated by Django 5.2.7 on 2026-01-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_invoicebookingservice_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebooking',
            name='booking_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], db_index=True, default='IN_HOUSE', max_length=25),
        ),
        migrations.AddField(
            model_name='invoicebookingservice',
            name='booking_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], db_index=True, default='OPD', max_length=25),
        ),
    ]
