# Generated by Django 5.2.7 on 2026-01-28 15:35

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_invoicebooking_booking_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='totalinvoice',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AddField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether payment has been verified'),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='invoice_number',
            field=models.CharField(db_index=True, default='INV-FNF-9A6CA4953E', help_text='Unique invoice identifier', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='issued_date',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or payment terms'),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='paid_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID, check number, UTR, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'method'], name='booking_pay_created_5d3615_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_verified', 'created_at'], name='booking_pay_is_veri_75a031_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['issued_date', 'status'], name='booking_tot_issued__a99387_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['patient', 'issued_date'], name='booking_tot_patient_27fe32_idx'),
        ),
    ]
