# Generated by Django 5.2.7 on 2026-01-28 17:35

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_payment_options_alter_totalinvoice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebooking',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='invoice_number',
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='invoice_number',
            field=models.CharField(db_index=True, help_text='Unique invoice identifier', max_length=50, unique=True),
        ),
    ]
