# Generated by Django 5.2.7 on 2026-01-28 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_remove_invoicebooking_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='booking.patient'),
        ),
    ]
