# Generated by Django 5.2.7 on 2026-01-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_payment_patient'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'content_type__model__in': ['venue', 'service', 'resource']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
