# Generated by Django 5.2.7 on 2026-02-03 05:57

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_package_content_type'),
        ('venue_manager', '0013_alter_venue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='service_package',
        ),
        migrations.RemoveField(
            model_name='invoicebookingservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='totalinvoice',
            name='service_bookings',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='totalinvoice',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='invoicebooking',
            name='booking_inv_user_id_85fe23_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicebooking',
            name='booking_inv_patient_7befa3_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoicebooking',
            name='booking_inv_start_d_19799e_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='booking_pay_invoice_0b8c79_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='booking_pay_patient_a7a6c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='booking_pay_created_5d3615_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='booking_pay_is_veri_75a031_idx',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_patient_7b5699_idx',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_user_id_929181_idx',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_status_b6c8c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_issued__a99387_idx',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_patient_27fe32_idx',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='venue_package',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='totalinvoice',
            name='notes',
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='booking_entity',
            field=models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service'), ('RESOURCE', 'Resource')], db_index=True, default='VENUE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.invoicebooking'),
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.service'),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='period_end',
            field=models.DateTimeField(db_index=True, default='2026-04-30 18:30:00+00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='period_start',
            field=models.DateTimeField(db_index=True, default='2025-12-31 18:30:00+00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoicebooking',
            name='booking_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], db_index=True, default='OPD', max_length=25),
        ),
        migrations.AlterField(
            model_name='invoicebooking',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.venue'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='booking',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.invoicebooking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='InvoiceBookingService',
        ),
    ]
