# Generated by Django 5.2.7 on 2026-02-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_remove_invoicebookingservice_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalinvoice',
            name='discount_amount',
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
