# Generated by Django 5.2.7 on 2026-02-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_remove_totalinvoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
