# Generated by Django 5.2.7 on 2026-02-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], max_length=20),
        ),
    ]
