# Generated by Django 5.2.7 on 2026-02-12 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_payment_paid_date_alter_location_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
