# Generated by Django 5.2.7 on 2026-02-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_alter_payment_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalinvoice',
            name='paid_date',
        ),
    ]
