# Generated by Django 5.2.7 on 2026-02-17 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_remove_totalinvoice_paid_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_date']},
        ),
        migrations.AlterModelOptions(
            name='totalinvoice',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'created_at'], name='booking_pay_invoice_0b8c79_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_verified'], name='booking_pay_is_veri_f4afff_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['booking', 'period_start'], name='booking_tot_booking_29cc0f_idx'),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['user', 'status'], name='booking_tot_user_id_6e19cb_idx'),
        ),
    ]
