# Generated by Django 5.2.7 on 2026-02-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_alter_payment_options_alter_totalinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicebooking',
            name='auto_continue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicebooking',
            name='order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
