# Generated by Django 5.2.7 on 2026-02-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_invoicebooking_auto_continue_invoicebooking_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
