# Generated by Django 5.2.7 on 2026-02-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_totalinvoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicebooking',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled')], db_index=True, default='DRAFT', max_length=25),
        ),
    ]
