# Generated by Django 5.2.7 on 2026-02-24 08:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_alter_invoicebooking_status'),
        ('venue_manager', '0014_remove_service_venue_service_venue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('booking_entity', models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service'), ('RESOURCE', 'Resource')], db_index=True, default='VENUE', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('booking_type', models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], db_index=True, default='OPD', max_length=25)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='DRAFT', max_length=25)),
                ('auto_continue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecondaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month'],
            },
        ),
        migrations.CreateModel(
            name='TernaryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=50)),
                ('booking_entity', models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service'), ('RESOURCE', 'Resource')], db_index=True, default='VENUE', max_length=20)),
                ('booking_type', models.CharField(choices=[('IN_HOUSE', 'In House'), ('OPD', 'OPD'), ('CLIENT_SIDE', 'Client Side')], db_index=True, default='OPD', max_length=25)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='DRAFT', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='package',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoicebooking',
            name='venue',
        ),
        migrations.RemoveIndex(
            model_name='totalinvoice',
            name='booking_tot_booking_29cc0f_idx',
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='package',
            name='period',
            field=models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_orders', to='booking.package'),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient'),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.service'),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.venue'),
        ),
        migrations.AddField(
            model_name='secondaryorder',
            name='primary_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_orders', to='booking.primaryorder'),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='secondary_order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.secondaryorder'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='totalinvoice',
            unique_together={('secondary_order', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['secondary_order', 'period_start'], name='booking_tot_seconda_efaea5_idx'),
        ),
        migrations.AddField(
            model_name='ternaryorder',
            name='secondary_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ternary_orders', to='booking.secondaryorder'),
        ),
        migrations.AddField(
            model_name='ternaryorder',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.service'),
        ),
        migrations.AlterUniqueTogether(
            name='secondaryorder',
            unique_together={('primary_order', 'year', 'month')},
        ),
        migrations.RemoveField(
            model_name='totalinvoice',
            name='booking',
        ),
        migrations.DeleteModel(
            name='InvoiceBooking',
        ),
    ]
