# Generated by Django 5.2.7 on 2026-02-25 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_primaryorder_secondaryorder_ternaryorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primaryorder',
            old_name='subtotal',
            new_name='total_bill',
        ),
        migrations.RemoveField(
            model_name='primaryorder',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='primaryorder',
            name='premium_amount',
        ),
        migrations.AddField(
            model_name='ternaryorder',
            name='package',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='ternary_orders', to='booking.package'),
            preserve_default=False,
        ),
    ]
