# Generated by Django 5.2.7 on 2026-02-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_rename_subtotal_primaryorder_total_bill_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secondaryorder',
            unique_together=set(),
        ),
    ]
