# Generated by Django 5.2.7 on 2026-02-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_alter_secondaryorder_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secondaryorder',
            unique_together={('primary_order', 'year', 'month')},
        ),
    ]
