# Generated by Django 5.2.7 on 2026-02-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_alter_secondaryorder_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondaryorder',
            options={'ordering': ['start_datetime', 'end_datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='secondaryorder',
            unique_together={('primary_order', 'start_datetime', 'end_datetime')},
        ),
    ]
