# Generated by Django 5.2.7 on 2026-02-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0038_alter_secondaryorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondaryorder',
            name='month',
        ),
        migrations.RemoveField(
            model_name='secondaryorder',
            name='year',
        ),
    ]
