# Generated by Django 5.2.7 on 2026-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_remove_secondaryorder_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ternaryorder',
            name='booking_entity',
            field=models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service'), ('RESOURCE', 'Resource')], db_index=True, default='SERVICE', max_length=20),
        ),
    ]
