# Generated by Django 5.2.7 on 2026-03-03 09:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_alter_ternaryorder_booking_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='totalinvoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ternary_invoices', to='booking.totalinvoice'),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='totalinvoice',
            name='ternary_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.ternaryorder'),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='secondary_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='booking.secondaryorder'),
        ),
        migrations.AlterField(
            model_name='totalinvoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='UNPAID', max_length=20),
        ),
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['ternary_order', 'period_start'], name='booking_tot_ternary_2d5b5e_idx'),
        ),
        migrations.AddConstraint(
            model_name='totalinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('secondary_order__isnull', False), ('ternary_order__isnull', True)), models.Q(('secondary_order__isnull', True), ('ternary_order__isnull', False)), _connector='OR'), name='invoice_must_link_to_exactly_one_order'),
        ),
    ]
