# Generated by Django 5.2.7 on 2026-03-03 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_alter_totalinvoice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='primaryorder',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
