# Generated by Django 5.2.7 on 2026-03-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_primaryorder_discount_amount_and_more'),
        ('venue_manager', '0014_remove_service_venue_service_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='ternaryorder',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_manager.venue'),
        ),
    ]
