# Generated by Django 5.2.7 on 2026-03-17 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_payment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalinvoice',
            name='issued_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
