# Generated by Django 5.2.7 on 2026-03-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_alter_totalinvoice_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryorder',
            name='status_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondaryorder',
            name='status_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ternaryorder',
            name='status_locked',
            field=models.BooleanField(default=False),
        ),
    ]
