# Generated by Django 6.0.3 on 2026-03-27 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_primaryorder_status_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryorder',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ternaryorder',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterConstraint(
            model_name='totalinvoice',
            name='invoice_must_link_to_exactly_one_order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('secondary_order__isnull', False), ('ternary_order__isnull', True)), models.Q(('secondary_order__isnull', True), ('ternary_order__isnull', False)), _connector='OR'), name='invoice_must_link_to_exactly_one_order', violation_error_message='Invoice must link to exactly one order (secondary or ternary, not both or neither).'),
        ),
    ]
