# Generated by Django 6.0.3 on 2026-04-09 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0047_primaryorder_client_address_and_more'),
        ('venue_manager', '0015_service_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('start_datetime', models.DateField(help_text='Booking start date')),
                ('end_datetime', models.DateField(help_text='Booking end date')),
                ('description', models.TextField(blank=True, help_text='Additional notes, special requirements, or reason for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(help_text='Staff member who created this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_manual_bookings', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text='Linked user account (optional for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_bookings', to='booking.patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_bookings', to='venue_manager.service')),
            ],
            options={
                'verbose_name': 'Contact Booking',
                'verbose_name_plural': 'Contact Bookings',
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['start_datetime', 'end_datetime'], name='booking_con_start_d_c097b8_idx'), models.Index(fields=['patient'], name='booking_con_patient_21c289_idx'), models.Index(fields=['booked_by'], name='booking_con_booked__f3308a_idx')],
            },
        ),
    ]
