# Generated by Django 6.0.3 on 2026-04-09 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_contactbooking'),
        ('venue_manager', '0015_service_service_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactbooking',
            options={'ordering': ['-start_date'], 'verbose_name': 'Contact Booking', 'verbose_name_plural': 'Contact Bookings'},
        ),
        migrations.RemoveIndex(
            model_name='contactbooking',
            name='booking_con_start_d_c097b8_idx',
        ),
        migrations.RenameField(
            model_name='contactbooking',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='contactbooking',
            old_name='start_datetime',
            new_name='start_date',
        ),
        migrations.AddIndex(
            model_name='contactbooking',
            index=models.Index(fields=['start_date', 'end_date'], name='booking_con_start_d_1ba079_idx'),
        ),
    ]
