# Generated by Django 6.0.3 on 2026-04-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_alter_contactbooking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='advance_payment',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='registration_fee',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_registration_fees_paid',
            field=models.BooleanField(default=False),
        ),
    ]
