# Generated by Django 6.0.3 on 2026-04-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_remove_patient_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='registration_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
