# Generated by Django 6.0.3 on 2026-04-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_package_registration_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondaryorder',
            name='is_registration_fee',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
