# Generated by Django 6.0.3 on 2026-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_secondaryorder_is_registration_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primaryorder',
            name='status',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='LOBBY', max_length=25),
        ),
        migrations.AlterField(
            model_name='secondaryorder',
            name='status',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='LOBBY', max_length=25),
        ),
        migrations.AlterField(
            model_name='ternaryorder',
            name='status',
            field=models.CharField(choices=[('LOBBY', 'Lobby'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled'), ('UNFULFILLED', 'Unfulfilled'), ('IN_PROGRESS', 'In Progress'), ('YET_TO_START', 'Yet To Start'), ('PARTIALLY_FULFILLED', 'Partially Fulfilled'), ('MODIFIED', 'Modified'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='LOBBY', max_length=25),
        ),
    ]
