# Generated by Django 6.0.3 on 2026-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_alter_primaryorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primaryorder',
            name='raw_dates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
