# Generated by Django 6.0.3 on 2026-05-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_alter_payment_invoice_alter_payment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('WALLET', 'Wallet'), ('WALLET_REFUND', 'Wallet Refund')], max_length=20),
        ),
    ]
