# Generated by Django 6.0.3 on 2026-05-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
