# Generated by Django 6.0.3 on 2026-05-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_patientdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdocument',
            name='file',
        ),
        migrations.CreateModel(
            name='PatientDocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='booking.patientdocument')),
            ],
        ),
    ]
