# Generated by Django 6.0.3 on 2026-05-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_remove_patientdocument_file_patientdocumentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdocumentfile',
            name='file',
            field=models.FileField(upload_to='patient_documents_report/'),
        ),
    ]
