# Generated by Django 6.0.3 on 2026-05-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_alter_patientdocumentfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id_proof_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_documents',
        ),
    ]
