# Generated by Django 6.0.3 on 2026-05-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0061_remove_patient_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank'), ('CHEQUE', 'Cheque'), ('RAZORPAY', 'Razorpay'), ('WALLET', 'Wallet'), ('WALLET_REFUND', 'Wallet Refund')], max_length=20),
        ),
    ]
