# Generated by Django 6.0.3 on 2026-07-01 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='totalinvoice',
            index=models.Index(fields=['user', 'patient'], name='booking_tot_user_id_9acde5_idx'),
        ),
    ]
