# Generated by Django 6.0.3 on 2026-09-02 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_patient_is_active_patient_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active', 'is_deleted'], name='booking_pat_is_acti_89ab29_idx'),
        ),
    ]
