# Generated by Django 6.0.3 on 2026-09-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_remove_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mapping_status',
            field=models.CharField(choices=[('AUTO_MAPPED', 'Auto Mapped'), ('UNMAPPED', 'Unmapped'), ('REVIEW', 'Review Required'), ('MANUAL', 'Manually Mapped')], default='UNMAPPED', max_length=20),
        ),
    ]
