# Generated by Django 6.0.3 on 2026-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_payment_mapping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mapping_meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
