# Generated by Django 6.0.3 on 2026-09-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_payment_mapping_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='affiliate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_probono',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='referred_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
